import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import { defineConfig, globalIgnores } from "eslint/config";

// Replaces the previous eslint-config-next setup: this app is a Vite + TanStack
// Router SPA, so the Next.js rules no longer apply to anything here.
export default defineConfig([
  globalIgnores([
    "dist/**",
    "build/**",
    ".next/**",
    ".vercel/**",
    "node_modules/**",
    "public/**",
    // Generated by `tsr generate` on every build.
    "src/routeTree.gen.ts",

    // design-sync (claude.ai/design) working directories. All three are
    // already in .gitignore or are sync inputs rather than app source, and
    // linting them added 2,608 errors that would fail CI:
    //   .ds-sync/     the staged converter scripts and their node_modules
    //   ds-bundle/    generated output — the bundle, cards and previews
    //   .design-sync/ committed sync inputs; the preview .tsx files import
    //                 from "canteen", a specifier that only resolves inside
    //                 the converter's own build, never this app's.
    ".ds-sync/**",
    "ds-bundle/**",
    ".design-sync/**",
  ]),

  js.configs.recommended,
  ...tseslint.configs.recommended,

  // Browser code. The react-hooks rules came from eslint-config-next before;
  // the plugin is now pulled in directly so the existing
  // `eslint-disable react-hooks/exhaustive-deps` comments still resolve.
  {
    files: ["src/**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks },
    languageOptions: {
      globals: { ...globals.browser },
    },
    rules: {
      // The two classic rules eslint-config-next enabled. The plugin's full
      // recommended set now also ships React-Compiler-era rules that flag
      // long-standing patterns all over this app; adopting those is a
      // separate piece of work, not part of getting the pipeline running.
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
    },
  },

  // Server functions, build config and maintenance scripts all run in Node.
  {
    files: [
      "api/**/*.ts",
      "src/server/**/*.ts",
      "scripts/**/*.js",
      "*.js",
      "*.mjs",
      "*.ts",
    ],
    languageOptions: {
      globals: { ...globals.node },
    },
  },

  // Test files run under node:test.
  {
    files: ["**/*.test.{ts,js}"],
    languageOptions: {
      globals: { ...globals.node },
    },
  },

  // One-off maintenance utilities, kept as CommonJS. The .cjs extension is what
  // makes them runnable at all: "type": "module" applies to .js, so as .js every
  // one of them died on `require is not defined in ES module scope`.
  {
    files: [
      "generate-icon.cjs",
      "scripts/rebuild-nobg.cjs",
      "scripts/upload-closed-plates.cjs",
      "scripts/upload-master-plate.cjs",
    ],
    languageOptions: {
      // These used to inherit node globals from the generic **/*.js block; as
      // .cjs they match nothing else, so declare the environment explicitly.
      sourceType: "commonjs",
      globals: { ...globals.node },
    },
    rules: {
      "@typescript-eslint/no-require-imports": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },

  {
    files: ["**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],
    },
  },
]);
